In [5]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

In [7]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
print("First 5 rows:")
print(df.head())

First 5 rows:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [11]:
print("\nDataset Shape:")
print(df.shape)

Dataset Shape:
(1000, 8)

In [13]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [15]:
print("\nDataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [17]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [19]:
print("\nDuplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0

In [21]:
categorical_cols = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

# Remove leading/trailing spaces
# Convert text to lowercase
for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [23]:
for col in categorical_cols:
    print("\n", col)
    print(df[col].unique())

 gender
['female' 'male']

 race/ethnicity
['group b' 'group c' 'group a' 'group d' 'group e']

 parental level of education
["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

 lunch
['standard' 'free/reduced']

 test preparation course
['none' 'completed']

In [25]:
score_cols = [
    "math score",
    "reading score",
    "writing score"
]

In [27]:
statistics = pd.DataFrame({

    "Mean": df[score_cols].mean(),

    "Median": df[score_cols].median(),

    "Standard Deviation": df[score_cols].std(),

    "Q1": df[score_cols].quantile(0.25),

    "Q2 (Median)": df[score_cols].quantile(0.50),

    "Q3": df[score_cols].quantile(0.75)

})

In [29]:
statistics

                 Mean  Median  Standard Deviation     Q1  Q2 (Median)    Q3
math score     66.089    66.0           15.163080  57.00         66.0  77.0
reading score  69.169    70.0           14.600192  59.00         70.0  79.0
writing score  68.054    69.0           15.195657  57.75         69.0  79.0

In [31]:
print(df[score_cols].describe())

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [33]:
df["Total Marks"] = df[score_cols].sum()

In [35]:
df["Percentage"] = (
    df["Total Marks"] / 300
) * 100

In [37]:
print(
    df[
        score_cols +
        ["Total Marks", "Percentage"]
    ])

     math score  reading score  writing score  Total Marks  Percentage
0            72             72             74          218   72.666667
1            69             90             88          247   82.333333
2            90             95             93          278   92.666667
3            47             57             44          148   49.333333
4            76             78             75          229   76.333333
..          ...            ...            ...          ...         ...
995          88             99             95          282   94.000000
996          62             55             55          172   57.333333
997          59             71             65          195   65.000000
998          68             78             77          223   74.333333
999          77             86             86          249   83.000000

[1000 rows x 5 columns]

In [43]:
performance = []

for percentage in df["Percentage"]:

    if percentage >= 90:
        performance.append("Excellent")

    elif percentage >= 75:
        performance.append("Very Good")

    elif percentage >= 60:
        performance.append("Good")

    elif percentage >= 50:
        performance.append("Average")

    else:
        performance.append("Needs Improvement")


df["Performance"] = performance

print(df[["Percentage", "Performance"]])

     Percentage        Performance
0     72.666667               Good
1     82.333333          Very Good
2     92.666667          Excellent
3     49.333333  Needs Improvement
4     76.333333          Very Good
..          ...                ...
995   94.000000          Excellent
996   57.333333            Average
997   65.000000               Good
998   74.333333               Good
999   83.000000          Very Good

[1000 rows x 2 columns]

In [49]:
for col in ["math score", "reading score", "writing score"]:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print("\nOutliers in", col)
    print(outliers[col])

Outliers in math score
17     18
59      0
145    22
338    24
466    26
787    19
842    23
980     8
Name: math score, dtype: int64

Outliers in reading score
59     17
76     26
211    28
327    23
596    24
980    24
Name: reading score, dtype: int64

Outliers in writing score
59     10
76     22
327    19
596    15
980    23
Name: writing score, dtype: int64

In [51]:
for col in ["math score", "reading score", "writing score"]:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print("\nOutliers in", col)
    print(outliers[col])

Outliers in math score
17     18
59      0
145    22
338    24
466    26
787    19
842    23
980     8
Name: math score, dtype: int64

Outliers in reading score
59     17
76     26
211    28
327    23
596    24
980    24
Name: reading score, dtype: int64

Outliers in writing score
59     10
76     22
327    19
596    15
980    23
Name: writing score, dtype: int64